---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    ConnectionString: AgByVaL1eSjrkh6jl0Xdf4/JkiRWvLzdK628s5AXOU94mVaraTB6z37gtNO+yI6lxJIylDhPMEq9nmKkrJK/xdYA9tYLtLSeg7Rf/ZmTd5CU2Lwlhg0w6BNdWR+cXIfsuERXUltvLnFzN8tMTwz1/s52n/ajCnezWcoPXu1fL4bWboUPvLr8PidS41lYSp0yPHM3TvZM9i1tQajmHDg8vXDgzdViabhlpKi6ZP0er9KC9bjhpQLTUbvz7Bnf5zpviluM7vZm7WrX/espX7WeP/zEzWJzxqpRGY1FavnPGFRMyU824Vjb6AxtuptILd6JktiVsNCmOVjrtUI+F35YhdBnxzD0lJ+oYwtxglJlc4UIThNER3ToCyB0XO7lKI3nRle0XNWdTZmahnWZ/ntJ7Bgv/a2IS4AUax2nbyhrd4ECikXL3JBu5Ss/WNEvjHw15C5pmEFrgCovSrQQr7IV3QIZQmhFU85NYZ4rE8+vDnrbhrarP7l81IhpG9Get/qBRrWsdWw7sZDrF5Y7HvhTD8GQaPPKaM1WT5m/yBLS73tGHJGeASprt5byMMJQB+ETws/icREtVtM93S6bYo1qkgzrnFwcZNbG43Sf/0awFqPu27JDVjlgOC0mA7sotNYuMtnaMEjzuGXiQ719jbu6m4kab2Hd5Huv+lfxZx/ZGHKOufm04GhF8Qj3IWJYKZiWR7Zq1x6l9L/xMTxp6VPM8lYrGKy4MrD+ZLdoNEXXjpeD8nz86cw9S2NJQJFWz2xhUgakHYR6UXeWHOf0eyzuL/ypU5BW/sRHmKTp03hPdwnbuLgKYXC8kXlyTIAXUIXhtxtLXSxdr2S4Amf+S1eT3irTk4DJvrt4AEuYp1AMUknf1Q==
    DatabaseName: AgBL/Ruj2GjTNkekDNArG5ofmNkYZNiDtdUCJA4sE477ewV14YOxWw8AUp6inBCiKnVQRfg/0H83KMDRvegun47bO4xNDty0im0wbtG5fDQVXX65CuKbTfdrJsEiXOZWI0PjlEf6BAQwdjYiRsRuQcemPMchq7AOhJ/qV5O/8+3s1WwURbruSNuGwOJhpCEcuwv1+hQDdhbnRUmlt8ZyMsbZkEI/1eh6A0JZWEDBkJQq+1iduEgHZ/VV+o2qicA2Fny08RqVS5K/UT3WIFuMrK8T4fh5CEUbppSrW47LwuqEaKNHMPn8t0JjPlgHR6/W1fHdSNDAlPBIw6FIsKf1brZ/RNnW7Vsyl7XzIYuE/M03j3h/GBBNJUb2/AIng+rNQS3hx4yVd6UeEJOZ860FHxkc+NzSrNzTItfs5xOgiQ5+K21VHq3tLHRgnllQf9FU8UeDevzX2XnaFjdneQjmrC+QN1RBFcRzTeWb3a0m5yCVKXGxL/z72hAtkYUdAfK/hHjDmC8OyevLIw6ZP/SLmN7PEdW0yK9ERo5APvhsE3/RAM3O7y07gJxqTipf93WC24WjI+T4NBxIbM6+EaOVPzmemSO+VpF5rjTlHbP2A8+5ds+1rVuX35vFELJLsScphIdokld+BiACHCJS8zpSb2nuegwXobzFA69tLWvinuhAd8/EfGS1oM5VfOwhxxSZ39BKJne/ovHuErMIOKA=
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: default
    type: Opaque
